C     QSQSQ$*$TURCO(1).isabel/S
C     **************************************************************
C   PROCEDURA PER STABILIRE SL'ISOMORFISMO DI 2 GRUPPI ABELIANI DATI
C   MEDIANTE TAVOLE DI MOLTIPLICAZIONE RISPETTO ALLA 1-A RIGA E ALLA 1-A
C   COLONNA (2 QUADRATI LATINI SIMMETRICI).
C   SI SFRUTTA IL SEGUENTE TEOREMA: 2 Q GRUPPI ABELIANI CONFORMI SONO ISOMORFI
C   L ED M SONO I DUE QL DACONFRONTARE. L'ORDINE = N
C       SE SI : TEST=.TRUE.
C       SE NO : TEST=.FALSE.
C
C     **************************************************************
C
      SUBROUTINE ISABEL(L,M,N,TEST)
      IMPLICIT INTEGER (A-Z)
      LOGICAL TEST
      PARAMETER (R=8)
      DIMENSION L(N,N),M(N,N),ML(R,R),MM(R,R),LKL(R),LKM(R),PL(R),LL(R)
      EQUIVALENCE (PL,LKL), (LL,LKM)
C
C     >> INIZIO
C
      TEST=.FALSE.
C
C * 1 COSTRUISCI IL MULTINSIEME (M.I.) DEI M.I. DELLE LUNGHEZZE DEI CICLI DI L: ML
C
      DO 20 J=1,N
      DO 10 I=1,N
 10   LL(I)=0
      CALL CAYLEY(L,N,1,J,PL,LL,NC)
C
C     IN LL IL M.I. DELLE LUNGHEZZE DEI CICLI. PL INUSATO
C
C   ORDINA LL
C
      CALL HSORT3(ML,N,N,LL,N,0)
      DO 20 K=1,N
        ML(K,J)=LL(K)
 20   CONTINUE
C
C     * 2 RIPETI(1) PER M.
C
      DO 30 J=1,N
      DO 25 I=1,N
 25   LL(I)=0
      CALL CAYLEY(M,N,1,J,PL,LL,NC)
      CALL HSORT3(MM,N,N,LL,N,0)
      DO 30 K=1,N
      MM(K,J)= LL(K)
 30   CONTINUE
C
C     COSTRUITI GLI INSIEMI DEI M.I.:
C   * 3. ORDINA I M.I. DELLE LUNGHEZZE DEI CICLI
C
      DO 40 K=1,N
        LKL(K)=K
 40     LKM(K)=K
      CALL HSORT3(ML,N,N,LKL,N,1)
      CALL HSORT3(MM,N,N,LKM,N,1)
C
C   * 4. CONFRONTO: SONO UGUALI I DUE M.I.?
C
      DO 50 I=1,N
        KL=LKL(I)
        KM=LKM(I)
        DO 50 K=1,N
        IF(ML(K,KL).NE.MM(K,KM)) GOTO 60   ! (ML.NE.MM)
 50    CONTINUE
C
C     KL=KM => L E' ISOMORFOAD M.
C
      TEST=.TRUE.     ! ESITO POSITIVO
      RETURN
C
 60   CONTINUE
C
C   KL.NE.KM => L NON ISOMORFO AD M.
C
      RETURN
      END
