	SUBROUTINE LISTAVA(A,I,L,N)
C	$TURCO(:).LISTVA/ISQ OCR_FORTRAN-PAG-10-16.pdf
C       COSTRUISCI LA LISTA -L- DEI VALORI I NEL LATIN SQUARE -A- 
C
	IMPLICIT INTEGER (A-Z)
	DIMENSION A(N,N), L(N)
	DO 20 J=1,N
	DO 10 K=1,N
	IF(A(K,J).EQ.I) GOTO 20
 10	CONTINUE
	STOP 1
 20	L(J)=K
	RETURN
	END